'use client'

import { useState } from 'react'
import { SyntaxIIResult } from '@/lib/types'
import { EuroScoreIIResult } from '@/lib/euroscore-ii'
import { EFTResult, FrailtyClass } from '@/lib/eft-score'

// ── Types ─────────────────────────────────────────────────────────────────────

interface Props {
  syntaxIScore: number
  hasLeftMain: boolean
  syntaxIIResult: SyntaxIIResult | null
  euroScoreResult: EuroScoreIIResult | null
  eftResult: EFTResult | null
  patientAge?: number
  patientGender?: 'male' | 'female'
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function syntaxICategory(score: number): { label: string; color: string } {
  if (score <= 22) return { label: 'Low', color: 'text-emerald-600' }
  if (score <= 32) return { label: 'Intermediate', color: 'text-amber-600' }
  return { label: 'High', color: 'text-red-600' }
}

function euroRiskLabel(mort: number): { label: string; color: string } {
  if (mort < 2) return { label: 'Low', color: 'text-emerald-600' }
  if (mort < 5) return { label: 'Moderate', color: 'text-amber-600' }
  return { label: 'High', color: 'text-red-600' }
}

const FRAILTY_LABELS: Record<FrailtyClass, { label: string; color: string }> = {
  robust:   { label: 'Robust', color: 'text-emerald-600' },
  prefrail: { label: 'Pre-Frail', color: 'text-amber-600' },
  frail:    { label: 'Frail', color: 'text-red-600' },
}

function formatPct(n: number): string { return n.toFixed(1) + '%' }
function formatInt(n: number): string { return Math.round(n).toString() }

// ── Export ─────────────────────────────────────────────────────────────────────

function exportToText(props: Props): string {
  const { syntaxIScore, hasLeftMain, syntaxIIResult, euroScoreResult, eftResult, patientAge, patientGender } = props
  const cat = syntaxICategory(syntaxIScore)
  const lines: string[] = []

  lines.push('═══════════════════════════════════════════')
  lines.push('      CORONARY RISK ASSESSMENT SUMMARY')
  lines.push('═══════════════════════════════════════════')
  lines.push('')

  // Patient
  if (patientAge || patientGender) {
    lines.push('PATIENT')
    if (patientAge) lines.push(`  Age:    ${patientAge} years`)
    if (patientGender) lines.push(`  Gender: ${patientGender === 'male' ? 'Male' : 'Female'}`)
    lines.push('')
  }

  // SYNTAX I
  lines.push('─── SYNTAX SCORE I (Anatomical Complexity) ───')
  lines.push(`  Score:       ${formatInt(syntaxIScore)}`)
  lines.push(`  Category:    ${cat.label} (${syntaxIScore <= 22 ? '≤22' : syntaxIScore <= 32 ? '23-32' : '≥33'})`)
  lines.push(`  Left Main:   ${hasLeftMain ? 'Yes' : 'No'}`)
  lines.push('')

  // SYNTAX II
  if (syntaxIIResult) {
    lines.push('─── SYNTAX SCORE II (PCI vs CABG) ───')
    lines.push(`  PCI:  SS2 = ${formatInt(syntaxIIResult.ss2PCI)}, 4-yr mortality = ${formatPct(syntaxIIResult.mortalityPCI)}`)
    lines.push(`  CABG: SS2 = ${formatInt(syntaxIIResult.ss2CABG)}, 4-yr mortality = ${formatPct(syntaxIIResult.mortalityCABG)}`)
    lines.push(`  p-value: ${syntaxIIResult.pValue < 0.001 ? '<0.001' : syntaxIIResult.pValue.toFixed(3)}`)
    lines.push(`  Recommendation: ${syntaxIIResult.recommendation === 'equipoise' ? 'Equipoise (PCI ≈ CABG)' : syntaxIIResult.recommendation + ' favored'}`)
    lines.push('')
  }

  // EuroSCORE II
  if (euroScoreResult) {
    const er = euroRiskLabel(euroScoreResult.predictedMortality)
    lines.push('─── EuroSCORE II (Surgical Risk) ───')
    lines.push(`  Predicted in-hospital mortality: ${formatPct(euroScoreResult.predictedMortality)}`)
    lines.push(`  Risk category: ${er.label}`)
    lines.push('')
  }

  // EFT
  if (eftResult) {
    const fl = FRAILTY_LABELS[eftResult.frailtyClass]
    lines.push('─── ESSENTIAL FRAILTY TOOLSET ───')
    lines.push(`  EFT Score:      ${eftResult.score}/5`)
    lines.push(`  Classification: ${fl.label}`)
    lines.push(`  CABG 1-yr mortality: ${eftResult.mortality1yr.cabg}%`)
    lines.push(`  CABG 5-yr mortality: ${eftResult.mortality5yr.cabg}%`)
    lines.push('')
  }

  // Overall
  lines.push('─── INTEGRATED ASSESSMENT ───')
  if (syntaxIIResult) {
    lines.push(`  Revascularization: ${syntaxIIResult.recommendation === 'equipoise' ? 'PCI or CABG (equipoise)' : syntaxIIResult.recommendation + ' favored'}`)
  }
  if (euroScoreResult) {
    lines.push(`  Surgical risk: ${formatPct(euroScoreResult.predictedMortality)} (EuroSCORE II)`)
  }
  if (eftResult) {
    lines.push(`  Frailty: ${FRAILTY_LABELS[eftResult.frailtyClass].label} (EFT ${eftResult.score}/5)`)
  }
  lines.push('')
  lines.push('═══════════════════════════════════════════')
  lines.push('Generated by SYNTAX Score Calculator')
  lines.push(`Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`)
  lines.push('')
  lines.push('References:')
  lines.push('• SYNTAX I: Sianos et al., EuroIntervention 2005')
  lines.push('• SYNTAX II: Farooq et al., Lancet 2013')
  lines.push('• EuroSCORE II: Nashef et al., EJCTS 2012')
  lines.push('• EFT: Solomon et al., JAHA 2021; Afilalo et al., JACC 2017')

  return lines.join('\n')
}

// ── Component ─────────────────────────────────────────────────────────────────

export function SummaryPanel(props: Props) {
  const { syntaxIScore, hasLeftMain, syntaxIIResult, euroScoreResult, eftResult, patientAge, patientGender } = props
  const cat = syntaxICategory(syntaxIScore)

  const handleCopy = () => {
    const text = exportToText(props)
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handlePrint = () => {
    const text = exportToText(props)
    const win = window.open('', '_blank')
    if (!win) return
    win.document.write(`<html><head><title>Coronary Risk Summary</title><style>
      body { font-family: 'Courier New', monospace; font-size: 12px; padding: 40px; line-height: 1.6; white-space: pre-wrap; }
      @media print { body { padding: 20px; } }
    </style></head><body>${text.replace(/\n/g, '<br/>')}</body></html>`)
    win.document.close()
    win.print()
  }

  const [copied, setCopied] = useState(false)

  return (
    <div className="rounded-xl border-2 border-gray-300 bg-white overflow-hidden shadow-md">
      {/* Header */}
      <div className="px-4 py-3 bg-gray-800 flex items-center justify-between">
        <div>
          <h2 className="text-sm font-bold text-white">
            📋 Risk Assessment Summary
          </h2>
          <p className="text-xs text-gray-400 mt-0.5">Combined results from all 4 scores</p>
        </div>
        <div className="flex gap-2">
          <button onClick={handleCopy}
            className="px-3 py-1.5 text-xs font-semibold bg-gray-700 hover:bg-gray-600 text-gray-200 rounded-lg transition-colors">
            {copied ? '✓ Copied' : '📋 Copy'}
          </button>
          <button onClick={handlePrint}
            className="px-3 py-1.5 text-xs font-semibold bg-blue-600 hover:bg-blue-500 text-white rounded-lg transition-colors">
            🖨 Print
          </button>
        </div>
      </div>

      <div className="p-4 space-y-3">
        {/* Patient */}
        {(patientAge || patientGender) && (
          <div className="flex items-center gap-4 text-xs text-gray-500 pb-2 border-b border-gray-100">
            {patientAge && <span>Age: <strong className="text-gray-800">{patientAge}</strong></span>}
            {patientGender && <span>Gender: <strong className="text-gray-800 capitalize">{patientGender}</strong></span>}
          </div>
        )}

        {/* Grid of 4 scores */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
          {/* SYNTAX I */}
          <div className="p-3 rounded-xl bg-blue-50 border border-blue-100">
            <p className="text-[10px] font-bold text-blue-500 uppercase tracking-wider mb-1">SYNTAX I</p>
            <p className="text-2xl font-bold text-blue-800 tabular-nums">{formatInt(syntaxIScore)}</p>
            <p className={`text-xs font-semibold ${cat.color}`}>{cat.label} complexity</p>
            <p className="text-[10px] text-gray-400 mt-0.5">LM: {hasLeftMain ? 'Yes' : 'No'}</p>
          </div>

          {/* SYNTAX II */}
          <div className="p-3 rounded-xl bg-indigo-50 border border-indigo-100">
            <p className="text-[10px] font-bold text-indigo-500 uppercase tracking-wider mb-1">SYNTAX II</p>
            {syntaxIIResult ? (
              <>
                <p className="text-lg font-bold text-indigo-800">
                  {syntaxIIResult.recommendation === 'equipoise' ? 'Equipoise' : syntaxIIResult.recommendation}
                </p>
                <div className="flex gap-2 mt-0.5">
                  <span className="text-[10px] text-gray-500">PCI {formatPct(syntaxIIResult.mortalityPCI)}</span>
                  <span className="text-[10px] text-gray-500">CABG {formatPct(syntaxIIResult.mortalityCABG)}</span>
                </div>
                <p className="text-[10px] text-gray-400">4-yr mortality</p>
              </>
            ) : (
              <p className="text-xs text-gray-400 mt-1">Enter clinical data</p>
            )}
          </div>

          {/* EuroSCORE II */}
          <div className="p-3 rounded-xl bg-rose-50 border border-rose-100">
            <p className="text-[10px] font-bold text-rose-500 uppercase tracking-wider mb-1">EuroSCORE II</p>
            {euroScoreResult ? (
              <>
                <p className="text-2xl font-bold tabular-nums"
                  style={{ color: euroScoreResult.riskCategory === 'low' ? '#059669' : euroScoreResult.riskCategory === 'moderate' ? '#d97706' : '#dc2626' }}>
                  {formatPct(euroScoreResult.predictedMortality)}
                </p>
                <p className={`text-xs font-semibold ${euroRiskLabel(euroScoreResult.predictedMortality).color}`}>
                  {euroRiskLabel(euroScoreResult.predictedMortality).label} risk
                </p>
                <p className="text-[10px] text-gray-400">In-hospital mortality</p>
              </>
            ) : (
              <p className="text-xs text-gray-400 mt-1">Enter clinical data</p>
            )}
          </div>

          {/* EFT */}
          <div className="p-3 rounded-xl bg-teal-50 border border-teal-100">
            <p className="text-[10px] font-bold text-teal-500 uppercase tracking-wider mb-1">Frailty (EFT)</p>
            {eftResult ? (
              <>
                <p className="text-2xl font-bold text-teal-800 tabular-nums">{eftResult.score}/5</p>
                <p className={`text-xs font-semibold ${FRAILTY_LABELS[eftResult.frailtyClass].color}`}>
                  {FRAILTY_LABELS[eftResult.frailtyClass].label}
                </p>
                <p className="text-[10px] text-gray-400">CABG 1yr: {eftResult.mortality1yr.cabg}%</p>
              </>
            ) : (
              <p className="text-xs text-gray-400 mt-1">Enter frailty data</p>
            )}
          </div>
        </div>

        {/* Decision guidance */}
        {syntaxIIResult && (
          <div className={`p-3 rounded-xl border ${
            syntaxIIResult.recommendation === 'PCI' ? 'bg-blue-50 border-blue-200' :
            syntaxIIResult.recommendation === 'CABG' ? 'bg-emerald-50 border-emerald-200' :
            'bg-amber-50 border-amber-200'
          }`}>
            <div className="flex items-start gap-2">
              <span className="text-base mt-0.5">
                {syntaxIIResult.recommendation === 'PCI' ? '🫀' : syntaxIIResult.recommendation === 'CABG' ? '🔪' : '⚖️'}
              </span>
              <div>
                <p className="text-sm font-bold text-gray-800">
                  {syntaxIIResult.recommendation === 'PCI' ? 'PCI Favored' :
                   syntaxIIResult.recommendation === 'CABG' ? 'CABG Favored' :
                   'Equipoise — Heart Team Discussion'}
                </p>
                <p className="text-xs text-gray-500 mt-0.5">
                  SYNTAX I: {cat.label} ({formatInt(syntaxIScore)})
                  {euroScoreResult && ` · Surgical risk: ${formatPct(euroScoreResult.predictedMortality)}`}
                  {eftResult && ` · Frailty: ${FRAILTY_LABELS[eftResult.frailtyClass].label}`}
                </p>
                {eftResult && eftResult.frailtyClass === 'frail' && syntaxIIResult.recommendation === 'CABG' && (
                  <p className="text-xs text-amber-700 mt-1 font-semibold">
                    ⚠️ Patient is frail — consider impact on CABG outcomes (1-yr: {eftResult.mortality1yr.cabg}%, 5-yr: {eftResult.mortality5yr.cabg}%)
                  </p>
                )}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
