'use client'

import { useState } from 'react'
import { SyntaxIIResult } from '@/lib/types'
import { EuroScoreIIResult } from '@/lib/euroscore-ii'
import { EFTResult, FrailtyClass } from '@/lib/eft-score'

// ── Types ─────────────────────────────────────────────────────────────────────

interface Props {
  syntaxIScore: number
  hasLeftMain: boolean
  syntaxIIResult: SyntaxIIResult | null
  euroScoreResult: EuroScoreIIResult | null
  eftResult: EFTResult | null
  patientAge?: number
  patientGender?: 'male' | 'female'
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function syntaxICategory(score: number): { label: string; color: string } {
  if (score <= 22) return { label: 'Low', color: 'text-emerald-600' }
  if (score <= 32) return { label: 'Intermediate', color: 'text-amber-600' }
  return { label: 'High', color: 'text-red-600' }
}

function euroRiskLabel(mort: number): { label: string; color: string } {
  if (mort < 2) return { label: 'Low', color: 'text-emerald-600' }
  if (mort < 5) return { label: 'Moderate', color: 'text-amber-600' }
  return { label: 'High', color: 'text-red-600' }
}

const FRAILTY_LABELS: Record<FrailtyClass, { label: string; color: string }> = {
  robust:   { label: 'Robust', color: 'text-emerald-600' },
  prefrail: { label: 'Pre-Frail', color: 'text-amber-600' },
  frail:    { label: 'Frail', color: 'text-red-600' },
}

function formatPct(n: number): string { return n.toFixed(1) + '%' }
function formatInt(n: number): string { return Math.round(n).toString() }

// ── Export ─────────────────────────────────────────────────────────────────────

function exportToText(props: Props): string {
  const { syntaxIScore, hasLeftMain, syntaxIIResult, euroScoreResult, eftResult, patientAge, patientGender } = props
  const cat = syntaxICategory(syntaxIScore)
  const lines: string[] = []

  lines.push('═══════════════════════════════════════════')
  lines.push('      CORONARY RISK ASSESSMENT SUMMARY')
  lines.push('═══════════════════════════════════════════')
  lines.push('')

  // Patient
  if (patientAge || patientGender) {
    lines.push('PATIENT')
    if (patientAge) lines.push(`  Age:    ${patientAge} years`)
    if (patientGender) lines.push(`  Gender: ${patientGender === 'male' ? 'Male' : 'Female'}`)
    lines.push('')
  }

  // SYNTAX I
  lines.push('─── SYNTAX SCORE I (Anatomical Complexity) ───')
  lines.push(`  Score:       ${formatInt(syntaxIScore)}`)
  lines.push(`  Category:    ${cat.label} (${syntaxIScore <= 22 ? '≤22' : syntaxIScore <= 32 ? '23-32' : '≥33'})`)
  lines.push(`  Left Main:   ${hasLeftMain ? 'Yes' : 'No'}`)
  lines.push('')

  // SYNTAX II
  if (syntaxIIResult) {
    lines.push('─── SYNTAX SCORE II ───')
    lines.push(`  PCI:  SS2 = ${formatInt(syntaxIIResult.ss2PCI)}, 4-yr mortality = ${formatPct(syntaxIIResult.mortalityPCI)}`)
    lines.push(`  CABG: SS2 = ${formatInt(syntaxIIResult.ss2CABG)}, 4-yr mortality = ${formatPct(syntaxIIResult.mortalityCABG)}`)
    lines.push('')
  }

  // EuroSCORE II
  if (euroScoreResult) {
    const er = euroRiskLabel(euroScoreResult.predictedMortality)
    lines.push('─── EuroSCORE II (Surgical Risk) ───')
    lines.push(`  Predicted in-hospital mortality: ${formatPct(euroScoreResult.predictedMortality)}`)
    lines.push(`  Risk category: ${er.label}`)
    lines.push('')
  }

  // EFT
  if (eftResult) {
    const fl = FRAILTY_LABELS[eftResult.frailtyClass]
    lines.push('─── ESSENTIAL FRAILTY TOOLSET ───')
    lines.push(`  EFT Score:      ${eftResult.score}/5`)
    lines.push(`  Classification: ${fl.label}`)
    lines.push(`  CABG 1-yr mortality: ${eftResult.mortality1yr.cabg}%`)
    lines.push(`  CABG 5-yr mortality: ${eftResult.mortality5yr.cabg}%`)
    lines.push('')
  }

  // Overall
  lines.push('─── INTEGRATED ASSESSMENT ───')
  if (euroScoreResult) {
    lines.push(`  Surgical risk: ${formatPct(euroScoreResult.predictedMortality)} (EuroSCORE II)`)
  }
  if (eftResult) {
    lines.push(`  Frailty: ${FRAILTY_LABELS[eftResult.frailtyClass].label} (EFT ${eftResult.score}/5)`)
  }
  lines.push('')
  lines.push('═══════════════════════════════════════════')
  lines.push('Generated by SYNTAX Score Calculator')
  lines.push(`Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`)
  lines.push('')
  lines.push('References:')
  lines.push('• SYNTAX I: Sianos et al., EuroIntervention 2005')
  lines.push('• SYNTAX II: Farooq et al., Lancet 2013')
  lines.push('• EuroSCORE II: Nashef et al., EJCTS 2012')
  lines.push('• EFT: Solomon et al., JAHA 2021; Afilalo et al., JACC 2017')

  return lines.join('\n')
}

// ── HTML Export ───────────────────────────────────────────────────────────

function generateHTML(props: Props): string {
  const { syntaxIScore, hasLeftMain, syntaxIIResult, euroScoreResult, eftResult, patientAge, patientGender } = props
  const cat = syntaxICategory(syntaxIScore)
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  const s2 = syntaxIIResult
  const es = euroScoreResult
  const ef = eftResult
  const fl = ef ? FRAILTY_LABELS[ef.frailtyClass] : null

  const recColor = s2?.recommendation === 'PCI' ? '#3b82f6' : s2?.recommendation === 'CABG' ? '#059669' : '#d97706'
  const recBg = s2?.recommendation === 'PCI' ? '#eff6ff' : s2?.recommendation === 'CABG' ? '#ecfdf5' : '#fffbeb'

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Coronary Risk Assessment Summary</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f8fafc; color: #1e293b; padding: 24px; }
  .container { max-width: 700px; margin: 0 auto; background: white; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 24px rgba(0,0,0,0.08); }
  .header { background: #1e293b; color: white; padding: 20px 24px; }
  .header h1 { font-size: 18px; font-weight: 700; }
  .header .sub { font-size: 12px; color: #94a3b8; margin-top: 4px; }
  .patient { padding: 12px 24px; background: #f1f5f9; font-size: 13px; color: #64748b; display: flex; gap: 16px; }
  .patient strong { color: #1e293b; }
  .body { padding: 20px 24px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 16px; }
  .card { padding: 16px; border-radius: 12px; border: 1px solid; }
  .card .label { font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 6px; }
  .card .value { font-size: 28px; font-weight: 700; line-height: 1; }
  .card .sub { font-size: 11px; color: #64748b; margin-top: 4px; }
  .card .tag { font-size: 11px; font-weight: 600; margin-top: 4px; }
  .c-blue { background: #eff6ff; border-color: #bfdbfe; }
  .c-blue .label { color: #3b82f6; }
  .c-blue .value { color: #1e40af; }
  .c-indigo { background: #eef2ff; border-color: #c7d2fe; }
  .c-indigo .label { color: #6366f1; }
  .c-indigo .value { color: #3730a3; }
  .c-rose { background: #fff1f2; border-color: #fecdd3; }
  .c-rose .label { color: #f43f5e; }
  .c-teal { background: #f0fdfa; border-color: #99f6e4; }
  .c-teal .label { color: #14b8a6; }
  .c-teal .value { color: #0f766e; }
  .rec { padding: 14px 16px; border-radius: 12px; margin-bottom: 16px; display: flex; align-items: flex-start; gap: 10px; }
  .rec .icon { font-size: 20px; flex-shrink: 0; }
  .rec .title { font-size: 14px; font-weight: 700; }
  .rec .detail { font-size: 11px; color: #64748b; margin-top: 3px; }
  .section { margin-bottom: 14px; }
  .section-title { font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; color: #94a3b8; margin-bottom: 8px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  table th { text-align: left; padding: 6px 8px; background: #f8fafc; color: #64748b; font-weight: 600; border-bottom: 1px solid #e2e8f0; }
  table td { padding: 6px 8px; border-bottom: 1px solid #f1f5f9; }
  table td.val { text-align: right; font-weight: 700; }
  .footer { padding: 16px 24px; background: #f8fafc; border-top: 1px solid #e2e8f0; }
  .footer p { font-size: 10px; color: #94a3b8; line-height: 1.5; }
  .green { color: #059669; } .amber { color: #d97706; } .red { color: #dc2626; }
  @media print { body { padding: 0; background: white; } .container { box-shadow: none; } }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>📋 Coronary Risk Assessment Summary</h1>
    <div class="sub">${date} · SYNTAX Score Calculator</div>
  </div>

  ${patientAge || patientGender ? `<div class="patient">
    ${patientAge ? `<span>Age: <strong>${patientAge} years</strong></span>` : ''}
    ${patientGender ? `<span>Gender: <strong>${patientGender === 'male' ? 'Male' : 'Female'}</strong></span>` : ''}
  </div>` : ''}

  <div class="body">
    <div class="grid">
      <div class="card c-blue">
        <div class="label">SYNTAX Score I</div>
        <div class="value">${formatInt(syntaxIScore)}</div>
        <div class="tag ${cat.color.replace('text-', '')}">${cat.label} complexity</div>
        <div class="sub">Left Main: ${hasLeftMain ? 'Yes' : 'No'}</div>
      </div>

      <div class="card c-indigo">
        <div class="label">SYNTAX Score II</div>
        ${s2 ? `
        <div class="value" style="font-size:22px">${s2.recommendation === 'equipoise' ? 'Equipoise' : s2.recommendation}</div>
        <div class="sub">PCI: ${formatPct(s2.mortalityPCI)} · CABG: ${formatPct(s2.mortalityCABG)}</div>
        <div class="sub">4-year mortality · p=${s2.pValue < 0.001 ? '<0.001' : s2.pValue.toFixed(3)}</div>
        ` : '<div class="sub">Not calculated</div>'}
      </div>

      <div class="card c-rose">
        <div class="label">EuroSCORE II</div>
        ${es ? `
        <div class="value" style="color:${es.riskCategory === 'low' ? '#059669' : es.riskCategory === 'moderate' ? '#d97706' : '#dc2626'}">${formatPct(es.predictedMortality)}</div>
        <div class="tag" style="color:${es.riskCategory === 'low' ? '#059669' : es.riskCategory === 'moderate' ? '#d97706' : '#dc2626'}">${euroRiskLabel(es.predictedMortality).label} risk</div>
        <div class="sub">In-hospital mortality</div>
        ` : '<div class="sub">Not calculated</div>'}
      </div>

      <div class="card c-teal">
        <div class="label">Frailty (EFT)</div>
        ${ef ? `
        <div class="value">${ef.score}/5</div>
        <div class="tag" style="color:${ef.frailtyClass === 'robust' ? '#059669' : ef.frailtyClass === 'prefrail' ? '#d97706' : '#dc2626'}">${fl?.label}</div>
        <div class="sub">CABG 1yr: ${ef.mortality1yr.cabg}% · 5yr: ${ef.mortality5yr.cabg}%</div>
        ` : '<div class="sub">Not assessed</div>'}
      </div>
    </div>


    ${s2 ? `<div class="section">
      <div class="section-title">Detailed Comparison</div>
      <table>
        <tr><th></th><th>PCI</th><th>CABG</th></tr>
        <tr><td>SYNTAX II Score</td><td class="val">${formatInt(s2.ss2PCI)}</td><td class="val">${formatInt(s2.ss2CABG)}</td></tr>
        <tr><td>4-Year Mortality</td><td class="val">${formatPct(s2.mortalityPCI)}</td><td class="val">${formatPct(s2.mortalityCABG)}</td></tr>
      </table>
    </div>` : ''}
  </div>

  <div class="footer">
    <p><strong>References:</strong> SYNTAX I: Sianos et al., EuroIntervention 2005 · SYNTAX II: Farooq et al., Lancet 2013 · EuroSCORE II: Nashef et al., EJCTS 2012 · EFT: Solomon et al., JAHA 2021; Afilalo et al., JACC 2017</p>
    <p style="margin-top:6px">This report is for educational purposes only. Clinical decisions should be made by qualified healthcare professionals.</p>
  </div>
</div>
</body>
</html>`
}

// ── Component ─────────────────────────────────────────────────────────────────

export function SummaryPanel(props: Props) {
  const { syntaxIScore, hasLeftMain, syntaxIIResult, euroScoreResult, eftResult, patientAge, patientGender } = props
  const cat = syntaxICategory(syntaxIScore)

  const handleCopy = () => {
    const text = exportToText(props)
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handlePrint = () => {
    const html = generateHTML(props)
    const win = window.open('', '_blank')
    if (!win) return
    win.document.write(html)
    win.document.close()
    win.print()
  }

  const handleShareHTML = () => {
    const html = generateHTML(props)
    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)

    // Try Web Share API first (mobile)
    if (navigator.share && navigator.canShare) {
      const file = new File([blob], 'coronary-risk-summary.html', { type: 'text/html' })
      if (navigator.canShare({ files: [file] })) {
        navigator.share({ files: [file], title: 'Coronary Risk Assessment Summary' }).catch(() => {
          // Fallback: download
          downloadBlob(blob)
        })
        return
      }
    }
    // Fallback: download file
    downloadBlob(blob)
  }

  const downloadBlob = (blob: Blob) => {
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'coronary-risk-summary.html'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const [copied, setCopied] = useState(false)

  return (
    <div className="rounded-xl border-2 border-gray-300 bg-white overflow-hidden shadow-md">
      {/* Header */}
      <div className="px-4 py-3 bg-gray-800 flex items-center justify-between">
        <div>
          <h2 className="text-sm font-bold text-white">
            📋 Risk Assessment Summary
          </h2>
          <p className="text-xs text-gray-400 mt-0.5">Combined results from all 4 scores</p>
        </div>
        <div className="flex gap-2">
          <button onClick={handleCopy}
            className="px-3 py-1.5 text-xs font-semibold bg-gray-700 hover:bg-gray-600 text-gray-200 rounded-lg transition-colors">
            {copied ? '✓ Copied' : '📋 Copy'}
          </button>
          <button onClick={handleShareHTML}
            className="px-3 py-1.5 text-xs font-semibold bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg transition-colors">
            📤 HTML
          </button>
          <button onClick={handlePrint}
            className="px-3 py-1.5 text-xs font-semibold bg-blue-600 hover:bg-blue-500 text-white rounded-lg transition-colors">
            🖨 Print
          </button>
        </div>
      </div>

      <div className="p-4 space-y-3">
        {/* Patient */}
        {(patientAge || patientGender) && (
          <div className="flex items-center gap-4 text-xs text-gray-500 pb-2 border-b border-gray-100">
            {patientAge && <span>Age: <strong className="text-gray-800">{patientAge}</strong></span>}
            {patientGender && <span>Gender: <strong className="text-gray-800 capitalize">{patientGender}</strong></span>}
          </div>
        )}

        {/* Grid of 4 scores */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
          {/* SYNTAX I */}
          <div className="p-3 rounded-xl bg-blue-50 border border-blue-100">
            <p className="text-[10px] font-bold text-blue-500 uppercase tracking-wider mb-1">SYNTAX I</p>
            <p className="text-2xl font-bold text-blue-800 tabular-nums">{formatInt(syntaxIScore)}</p>
            <p className={`text-xs font-semibold ${cat.color}`}>{cat.label} complexity</p>
            <p className="text-[10px] text-gray-400 mt-0.5">LM: {hasLeftMain ? 'Yes' : 'No'}</p>
          </div>

          {/* SYNTAX II */}
          <div className="p-3 rounded-xl bg-indigo-50 border border-indigo-100">
            <p className="text-[10px] font-bold text-indigo-500 uppercase tracking-wider mb-1">SYNTAX II</p>
            {syntaxIIResult ? (
              <>
                <div className="space-y-0.5 mt-0.5">
                  <p className="text-[11px] text-gray-600">PCI {formatPct(syntaxIIResult.mortalityPCI)}</p>
                  <p className="text-[11px] text-gray-600">CABG {formatPct(syntaxIIResult.mortalityCABG)}</p>
                </div>
                <p className="text-[10px] text-gray-400 mt-1">4-yr mortality</p>
              </>
            ) : (
              <p className="text-xs text-gray-400 mt-1">Enter clinical data</p>
            )}
          </div>

          {/* EuroSCORE II */}
          <div className="p-3 rounded-xl bg-rose-50 border border-rose-100">
            <p className="text-[10px] font-bold text-rose-500 uppercase tracking-wider mb-1">EuroSCORE II</p>
            {euroScoreResult ? (
              <>
                <p className="text-2xl font-bold tabular-nums"
                  style={{ color: euroScoreResult.riskCategory === 'low' ? '#059669' : euroScoreResult.riskCategory === 'moderate' ? '#d97706' : '#dc2626' }}>
                  {formatPct(euroScoreResult.predictedMortality)}
                </p>
                <p className={`text-xs font-semibold ${euroRiskLabel(euroScoreResult.predictedMortality).color}`}>
                  {euroRiskLabel(euroScoreResult.predictedMortality).label} risk
                </p>
                <p className="text-[10px] text-gray-400">In-hospital mortality</p>
              </>
            ) : (
              <p className="text-xs text-gray-400 mt-1">Enter clinical data</p>
            )}
          </div>

          {/* EFT */}
          <div className="p-3 rounded-xl bg-teal-50 border border-teal-100">
            <p className="text-[10px] font-bold text-teal-500 uppercase tracking-wider mb-1">Frailty (EFT)</p>
            {eftResult ? (
              <>
                <p className="text-2xl font-bold text-teal-800 tabular-nums">{eftResult.score}/5</p>
                <p className={`text-xs font-semibold ${FRAILTY_LABELS[eftResult.frailtyClass].color}`}>
                  {FRAILTY_LABELS[eftResult.frailtyClass].label}
                </p>
                <p className="text-[10px] text-gray-400">CABG 1yr: {eftResult.mortality1yr.cabg}%</p>
              </>
            ) : (
              <p className="text-xs text-gray-400 mt-1">Enter frailty data</p>
            )}
          </div>
        </div>


      </div>
    </div>
  )
}
